[package]
name = "dir-test"
version = "0.1.0"
edition = "2021"

[dependencies]
dir-test-macros = { version = "0.1.0", path = "../macros"  }

[dev-dependencies]
trybuild = { version = "1.0", features = ["diff"] }