[package]
name = "dir-test-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc_macro = true

[dependencies]
syn = { version = "1.0", features = ["full"] }
proc-macro2 = "1.0"
quote = "1.0"
glob = "0.3"